name: shuttla
description: Implementation of a simple Demand Responsive Transport System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #remote data transfer
  dio: any
  #stacked services
  get: 4.0.0
  #dependency injection
  get_it: ^7.0.0
  #localization
  intl: ^0.17.0
  #state management
  provider: ^5.0.0
  equatable: ^2.0.0
  shared_preferences:
  ##Geolocation
  flutter_google_places: any
  geocoding: any
  geolocator: 7.3.0
  google_maps_flutter: any
  google_maps_webservice: any
  flutter_bloc: ^7.1.0
  gap: ^2.0.0

  # Firebase services
  firebase_core: 1.0.0
  firebase_messaging: any
  firebase_storage: any
  firebase_auth: 1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
